from net_conf import *

RULES_DECODER_STATE_SIZE = RULES_QUERY_ENCODER_STATE_SIZE * 2
WORDS_DECODER_STATE_SIZE = RULES_ENCODER_STATE_SIZE * 2

DJANGO_DATA_SET_TYPE = 'DJANGO'
HS_DATA_SET_TYPE = 'HS'

DATA_SET_TYPE = DJANGO_DATA_SET_TYPE

DATA_SET_BASE_DIR = '../django_data_set/data/'
DATA_SET_NAME = 'django_data_set_v2'
FULL_DATA_SET_NAME = 'django.cleaned.dataset.freq3.par_info.refact.space_only.order_by_ulink_len.bin'

MODEL_SAVE_PATH = 'trained/'
RULES_MODEL_BASE_NAME = 'model_rules'
WORDS_MODEL_BASE_NAME = 'model_words'
SELECTOR_MODEL_BASE_NAME = RULES_MODEL_BASE_NAME + '_selector'

BEST_RULES_MODEL_BASE_NAME = RULES_MODEL_BASE_NAME + '-6'
BEST_WORDS_MODEL_BASE_NAME = WORDS_MODEL_BASE_NAME + '-3'
BEST_SELECTOR_MODEL_BASE_NAME = SELECTOR_MODEL_BASE_NAME + '-2'

PRETRAIN_SAVE_PATH = 'pretrained/'
PRETRAIN_BASE_NAME = 'pretrain'

RULES_BEAM_SIZE = 15
RULE_TREE_BEAM_SIZE = 3
