ENCODER_INPUT_SIZE = 256
ENCODER_STATE_SIZE = 64
ENCODER_LAYERS = 2

CODE_DECODER_LAYERS = 3
CODE_DECODER_ATTENTION = False

WORD_DECODER_LAYERS = 2
WORD_COPY_NET = True
WORD_DECODER_ATTENTION = False

DROPOUT_PROB = 0.95
