ENCODER_INPUT_SIZE = 256
ENCODER_STATE_SIZE = 64
ENCODER_LAYERS = 2

RULES_DECODER_LAYERS = 2
CODE_DECODER_ATTENTION = False

WORD_DECODER_LAYERS = 3

DROPOUT_PROB = 0.95
ENCODER_DROPOUT_PROB = 0.95

BATCH_SIZE = 6

L2_COEFFICIENT = 1e-5
