RULES_QUERY_ENCODER_INPUT_SIZE = 256
RULES_QUERY_ENCODER_STATE_SIZE = 64
RULES_QUERY_ENCODER_LAYERS = 2

RULES_DECODER_LAYERS = 3
RULES_DECODER_ATTENTION_SIZE = 128

WORDS_QUERY_ENCODER_INPUT_SIZE = 256
WORDS_QUERY_ENCODER_STATE_SIZE_BY_LAYER = [64, 48]
WORDS_QUERY_ENCODER_STATE_SIZE = WORDS_QUERY_ENCODER_STATE_SIZE_BY_LAYER[-1]
WORDS_QUERY_ENCODER_LAYERS = len(WORDS_QUERY_ENCODER_STATE_SIZE_BY_LAYER)

RULES_ENCODER_INPUT_SIZE = 128
RULES_ENCODER_STATE_SIZE_BY_LAYER = [64, 48]
RULES_ENCODER_STATE_SIZE = RULES_ENCODER_STATE_SIZE_BY_LAYER[-1]
RULES_ENCODER_LAYERS = len(RULES_ENCODER_STATE_SIZE_BY_LAYER)

WORD_DECODER_LAYERS = 2

DROPOUT_PROB = 0.95
ENCODER_DROPOUT_PROB = 0.95

BATCH_SIZE = 6

L2_COEFFICIENT = 1e-5
